version: "3"

services:
  pg:
    image: postgres # use latest official postgres version
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
#      - "8080:80"
    volumes:
      - pg-data:/var/lib/postgresql/data/ # persist data even if container shuts down

  blog:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      CONFIG_NAME: ProductionConfig
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://app:password@pg/blog
    ports:
      - "5080:80"
    depends_on:
      - pg

volumes:
  pg-data:


